# Default values for store-frontend
replicaCount: 1

image:
  repository: quay.io/mcombi/store-frontend
  tag: "1.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

route:
  enabled: true
  host: ""
  tls:
    enabled: false
    termination: edge

resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
  # requests:
  #   cpu: 50m
  #   memory: 64Mi

probes:
  enabled: true
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 20

env: []
  # - name: REACT_APP_API_URL
  #   value: "http://store-backend:8080"

nodeSelector: {}

tolerations: []

affinity: {}

