apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: store-showcase-template
  namespace: store-showcase
  title: Store Showcase
  description: Create a Store Showcase Application
  tags:
    - recommended
    - java
    - quarkus
    - maven
spec:
  owner: rhdh 
  type: service
  parameters:
    - title:  Information for FrontEnd Application
      required:
        - fe_component_id
        - number_of_users
      properties:
        fe_component_id:
          title: Name
          type: string
          description: Unique name of the component
          default: store-frontend
          ui:field: EntityNamePicker
          maxLength: 18
        number_of_users:
          title: Number of Users
          type: string
          description: Expected number of users for the application
          enum:
            - 10-100
            - 100-1000
            - 1000-10000
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
          default: The frontend application for the store
    - title: Provide Information for Backend Orders Application
      required:
        - be_or_component_id
        - be_or_java_package_name
      properties:
        be_or_component_id:
          title: Name
          type: string
          description: Unique name of the component
          default: orders-backend
          ui:field: EntityNamePicker
          maxLength: 18
        be_or_group_id:
          title: Group Id
          type: string
          default: com.redhat.demo
          description: Maven Group Id
        be_or_artifact_id:
          title: Artifact Id
          type: string
          default: orders-backend
          description: Maven Artifact Id
        be_or_java_package_name:
          title: Java Package Name
          default: com.redhat.demo
          type: string
          description: Name for the java package. eg (com.redhat.blah)
        be_or_description:
          title: Description
          type: string
          description: Help others understand what this website is for.
          default: The backend to manage orders for the store
    - title: Provide Information for Backend Store Application
      required:
        - be_st_component_id
        - be_st_java_package_name
      properties:
        be_st_component_id:
          title: Name
          type: string
          description: Unique name of the component
          default: store-backend
          ui:field: EntityNamePicker
          maxLength: 18
        be_st_group_id:
          title: Group Id
          type: string
          default: com.redhat.demo
          description: Maven Group Id
        be_st_artifact_id:
          title: Artifact Id
          type: string
          default: store-backend
          description: Maven Artifact Id
        be_st_java_package_name:
          title: Java Package Name
          default: com.redhat.demo
          type: string
          description: Name for the java package. eg (com.redhat.blah)
        be_st_description:
          title: Description
          type: string
          description: Help others understand what this website is for.
          default: The orders backend application for the store
    - title: Provide Information for The Database
      required:
        - db_username
        - db_name
      properties:
        db_username:
          title: Database Username
          type: string
          description: Unique name of the component
          default: ordersuser
          ui:field: EntityNamePicker
          maxLength: 18
        db_name:
          title: Database Name
          type: string
          description: Unique name of the component
          default: ordersdb
          ui:field: EntityNamePicker
          maxLength: 18
    - title: Provide Information for Backend kafka Configuration
      required:
        - kafka_topic_name
        - kafka_cluster_name
        
      properties:
        kafka_topic_name:
          title: Topic Name
          type: string
          default: orders-out
          description: Kafka Topic Name to create
        kafka_cluster_name:
          title: Topic Cluster Name
          type: string
          default: orders-cluster
          description: Name of the Kafka Cluster to create the topic in
        # kafka_replicas:
        #   title: Replicas
        #   type: string
        #   description: Select the number of replicas for the Kafka Cluster.
        #   default: "3"
    - title: Provide Image Registry Information
      required:
        - image_registry
      properties:
        image_registry:
          title: Image Registry
          type: string
          enum:
            - OpenShift
            - Quay
      dependencies:
        image_registry:
          oneOf:
            - properties:
                image_registry:
                  enum:
                    - OpenShift
                image_host:
                  title: Image Host
                  type: string
                  description: Host for storing image
                  default: image-registry.openshift-image-registry.svc:5000
                image_tag:
                  title: Image Tag
                  default: latest
                  type: string
                  description: Build Image tag
            - properties:
                image_registry:
                  enum:
                    - Quay
                image_host:
                  title: Image Host
                  type: string
                  description: Host for storing image
                  default: quay.apps.cluster-vngth.vngth.sandbox1898.opentlc.com
                image_password:
                  title: Password
                  type: string
                  description: Your Quay password
                  ui:field: Secret
                image_tag:
                  title: Image Tag
                  default: latest
                  type: string
                  description: Build Image tag

    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: gitlab-gitlab.apps.cluster-vngth.vngth.sandbox1898.opentlc.com
              enum:
                - gitlab-gitlab.apps.cluster-vngth.vngth.sandbox1898.opentlc.com

  steps:
    - id: template-frontend
      name: Fetch Frontend  Template
      action: fetch:template
      input:
        url: ./skeleton/store-frontend
        values:
          component_id: ${{ parameters.fe_component_id }}
          description: ${{ parameters.fe_description }}
          namespace: store-showcase
          owner: ${{ user.entity.metadata.name }}
          cluster: apps.cluster-vngth.vngth.sandbox1898.opentlc.com
          host: ${{ parameters.repo.host }}
          destination: ${{ user.entity.metadata.name }}/${{ parameters.fe_component_id }}
          port: 8080
          gitops_namespace: rhdh-gitops
        targetPath: ./${{ user.entity.metadata.name }}-${{parameters.fe_component_id}}

    - id: template-frontend-gitops
      name: Fetch Frontend Gitops Template
      action: fetch:template
      input:
        url: ./manifest/argocd/store-frontend-config
        values:
          component_id: store-frontend-config
          description: 'Gitops resources for the store frontend'
          namespace: store-showcase
          owner: ${{ user.entity.metadata.name }}
          cluster: apps.cluster-vngth.vngth.sandbox1898.opentlc.com
          host: ${{ parameters.repo.host }}
          destination: ${{ user.entity.metadata.name }}/${{parameters.fe_component_id}}-gitops
          port: 8080
          gitops_namespace: rhdh-gitops
        targetPath: ./${{ user.entity.metadata.name }}-${{parameters.fe_component_id}}-gitops
    
    - id: template-store-backend
      name: Fetch Store Backend Template
      action: fetch:template
      input:
        url: ./skeleton/store-backend
        values:
          component_id: ${{ parameters.be_st_component_id }}
          description: ${{ parameters.be_st_description }}
          namespace: store-showcase
          owner: ${{ user.entity.metadata.name }}
          cluster: apps.cluster-vngth.vngth.sandbox1898.opentlc.com
          host: ${{ parameters.repo.host }}
          destination: ${{ user.entity.metadata.name }}/${{ parameters.be_st_component_id }}
          port: 8080
          gitops_namespace: rhdh-gitops
        targetPath: ./${{ user.entity.metadata.name }}-${{parameters.be_st_component_id}}

    - id: template-store-backend-gitops
      name: Fetch Store Backend Gitops Template
      action: fetch:template
      input:
        url: ./manifest/argocd/store-config
        values:
          component_id: store-config
          description: 'Gitops resources for the store backend'
          namespace: store-showcase
          owner: ${{ user.entity.metadata.name }}
          cluster: apps.cluster-vngth.vngth.sandbox1898.opentlc.com
          host: ${{ parameters.repo.host }}
          destination: ${{ user.entity.metadata.name }}/${{parameters.be_st_component_id}}-gitops
          port: 8080
          gitops_namespace: rhdh-gitops
        targetPath: ./${{ user.entity.metadata.name }}-${{parameters.be_st_component_id}}-gitops
    
    - id: template-orders-backend
      name: Fetch Orders Backend Template
      action: fetch:template
      input:
        url: ./skeleton/orders-backend
        values:
          component_id: ${{ parameters.be_or_component_id }}
          description: ${{ parameters.be_or_description }}
          namespace: store-showcase
          owner: ${{ user.entity.metadata.name }}
          cluster: apps.cluster-vngth.vngth.sandbox1898.opentlc.com
          host: ${{ parameters.repo.host }}
          destination: ${{ user.entity.metadata.name }}/${{ parameters.be_or_component_id }}
          port: 8080
          gitops_namespace: rhdh-gitops
        targetPath: ./${{ user.entity.metadata.name }}-${{parameters.be_or_component_id}}

    - id: template-orders-backend-gitops
      name: Fetch Orders Backend Gitops Template
      action: fetch:template
      input:
        url: ./manifest/argocd/orders-config
        values:
          component_id: orders-config
          description: 'Gitops resources for the orders backend'
          namespace: store-showcase
          owner: ${{ user.entity.metadata.name }}
          cluster: apps.cluster-vngth.vngth.sandbox1898.opentlc.com
          host: ${{ parameters.repo.host }}
          destination: ${{ user.entity.metadata.name }}/${{parameters.be_or_component_id}}-gitops
          port: 8080
          gitops_namespace: rhdh-gitops
        targetPath: ./${{ user.entity.metadata.name }}-${{parameters.be_or_component_id}}-gitops
    

    - id: publish-frontend
      name: Publish Frontend
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ user.entity.metadata.name }}&repo=${{parameters.fe_component_id}}"
        repoVisibility: public
        defaultBranch: main
        sourcePath: ./${{ user.entity.metadata.name }}-${{parameters.fe_component_id}}

    - id: publish-frontend-gitops
      name: Publish Frontend Gitops
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ user.entity.metadata.name }}&repo=${{parameters.fe_component_id}}-gitops"
        repoVisibility: public
        defaultBranch: main
        sourcePath: ./${{ user.entity.metadata.name }}-${{parameters.fe_component_id}}-gitops

    - id: publish-store-backend
      name: Publish Store Backend
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ user.entity.metadata.name }}&repo=${{parameters.be_st_component_id}}"
        repoVisibility: public
        defaultBranch: main
        sourcePath: ./${{ user.entity.metadata.name }}-${{parameters.be_st_component_id}}

    - id: publish-store-backend-gitops
      name: Publish Store Backend Gitops
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ user.entity.metadata.name }}&repo=${{parameters.be_st_component_id}}-gitops"
        repoVisibility: public
        defaultBranch: main
        sourcePath: ./${{ user.entity.metadata.name }}-${{parameters.be_st_component_id}}-gitops

    - id: publish-orders-backend
      name: Publish Orders Backend
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ user.entity.metadata.name }}&repo=${{parameters.be_or_component_id}}"
        repoVisibility: public
        defaultBranch: main
        sourcePath: ./${{ user.entity.metadata.name }}-${{parameters.be_or_component_id}}

    - id: publish-orders-backend-gitops
      name: Publish Orders Backend Gitops
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ user.entity.metadata.name }}&repo=${{parameters.be_or_component_id}}-gitops"
        repoVisibility: public
        defaultBranch: main
        sourcePath: ./${{ user.entity.metadata.name }}-${{parameters.be_or_component_id}}-gitops

    - id: register-frontend
      name: Register Frontend
      action: catalog:register
      owner: ${{ user.entity.metadata.name }}
      group: ${{ user.entity.metadata.group}}
      input:
        catalogInfoUrl: "https://${{ parameters.repo.host }}/${{ user.entity.metadata.name }}/${{ parameters.fe_component_id }}/-/blob/main/catalog-info.yaml"
    
    - id: register-store-backend
      name: Register Store Backend
      action: catalog:register
      owner: ${{ user.entity.metadata.name }}
      group: ${{ user.entity.metadata.group}}
      input:
        catalogInfoUrl: "https://${{ parameters.repo.host }}/${{ user.entity.metadata.name }}/${{ parameters.be_st_component_id }}/-/blob/main/catalog-info.yaml"

    - id: register-orders-backend
      name: Register Orders Backend
      owner: ${{ user.entity.metadata.name }}
      group: ${{ user.entity.metadata.group}}
      action: catalog:register
      input:
        catalogInfoUrl: "https://${{ parameters.repo.host }}/${{ user.entity.metadata.name }}/${{ parameters.be_or_component_id }}/-/blob/main/catalog-info.yaml"

    - id: template-gitops-common-config
      name: Generating Deployment for Common Config
      action: fetch:template
      input:
        url: ./manifest/argocd/store-common-config/
        copyWithoutTemplating: []
        values:
          component_id: ${{ parameters.be_or_component_id }}
          description: 'Gitops resources for the common config'
          namespace: store-showcase
          owner: ${{ user.entity.metadata.name }}
          cluster: apps.cluster-vngth.vngth.sandbox1898.opentlc.com
          host: ${{ parameters.repo.host }}
          destination: ${{ user.entity.metadata.name }}/store-infra-gitops
          port: 8080
          gitops_namespace: rhdh-gitops
        targetPath: ./${{ user.entity.metadata.name }}-store-infra-gitops

    - id: publish-infragitops
      name: Publishing to Resource Repository
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ user.entity.metadata.name }}&repo=store-infra-gitops"
        repoVisibility: public
        defaultBranch: main
        title: gitops resources for infra
        description: gitops resources for infra
        sourcePath: ./${{ user.entity.metadata.name }}-store-infra-gitops

    - id: template-orders-backend-pipeline
      name: Generating Deployment for Orders Backend Pipeline
      action: fetch:template
      input:
        url: ./skeleton/quarkus-pipeline/
        copyWithoutTemplating: []
        values:
          component_id: orders-backend-pipeline
          description: 'Gitops resources for the common config'
          namespace: store-showcase
          owner: ${{ user.entity.metadata.name }}
          cluster: apps.cluster-vngth.vngth.sandbox1898.opentlc.com
          host: ${{ parameters.repo.host }}
          destination: ${{ user.entity.metadata.name }}/${{parameters.be_or_component_id}}-pipeline
          port: 8080
          gitops_namespace: rhdh-gitops
        targetPath: ./${{ user.entity.metadata.name }}-${{parameters.be_or_component_id}}-pipeline

    - id: publish-orders-backend-pipeline
      name: Publish Orders Backend Pipeline
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ user.entity.metadata.name }}&repo=${{parameters.be_or_component_id}}-pipeline"
        repoVisibility: public
        defaultBranch: main
        sourcePath: ./${{ user.entity.metadata.name }}-${{parameters.be_or_component_id}}-pipeline

    - id: template-store-backend-pipeline
      name: Generating Deployment for Store Backend Pipeline
      action: fetch:template
      input:
        url: ./skeleton/quarkus-pipeline/
        copyWithoutTemplating: []
        values:
          component_id: store-backend-pipeline
          description: 'Gitops resources for store backend pipeline'
          namespace: store-showcase
          owner: ${{ user.entity.metadata.name }}
          cluster: apps.cluster-vngth.vngth.sandbox1898.opentlc.com
          host: ${{ parameters.repo.host }}
          destination: ${{ user.entity.metadata.name }}/${{parameters.be_st_component_id}}-pipeline
          port: 8080
          gitops_namespace: rhdh-gitops
        targetPath: ./${{ user.entity.metadata.name }}-${{parameters.be_st_component_id}}-pipeline

    - id: publish-orders-backend-pipeline
      name: Publish Orders Backend Pipeline
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ user.entity.metadata.name }}&repo=${{parameters.be_st_component_id}}-pipeline"
        repoVisibility: public
        defaultBranch: main
        sourcePath: ./${{ user.entity.metadata.name }}-${{parameters.be_st_component_id}}-pipeline
    

    - id: create-argocd-resources-infra
      name: Create Argo CD Infra
      action: argocd:create-resources
      input:
        appName: store-infra-bootstrap
        argoInstance: main
        namespace: store-showcase
        createNamespace: true
        repoUrl: https://${{ parameters.repo.host }}/${{ user.entity.metadata.name }}/store-infra-gitops.git
        path: 'argocd/'

    - id: create-argocd-resources-orders
      name: Create Argo CD Infra
      action: argocd:create-resources
      input:
        appName: ${{parameters.be_or_component_id}}-bootstrap
        argoInstance: main
        namespace: store-showcase
        createNamespace: true
        repoUrl: https://${{ parameters.repo.host }}/${{ user.entity.metadata.name }}/orders-backend-gitops.git
        path: 'argocd/'

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish-frontend.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register-frontend.output.entityRef }}
      - title: Source Code Repository
        url: ${{ steps.publish-store-backend.output.remoteUrl }}
        icon: catalog
        entityRef: ${{ steps.register-store-backend.output.entityRef }}
      - title: Source Code Repository
        url: ${{ steps.publish-orders-backend.output.remoteUrl }}
        icon: catalog
        entityRef: ${{ steps.register-orders-backend.output.entityRef }}