{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "orders-backend.fullname" . }}-monitor
  labels:
    {{- include "orders-backend.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
      port: http
      scheme: http
  selector:
    matchLabels:
      {{- include "orders-backend.selectorLabels" . | nindent 6 }}
{{- end }}

