apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-store.fullname" . }}-service
  labels:
    {{- include "spring-store.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "spring-store.selectorLabels" . | nindent 4 }}

